export default {
  FIND_DATA_SUCCESS: "ค้นหาข้อมูลสำเร็จ",
  INSERT_SUCCESS: "เพิ่มข้อมูลสำเร็จ",
  UPDATE_SUCCESS: "แก้ไขข้อมูลสำเร็จ",
  DELETE_SUCCESS: "ลบข้อมูลสำเร็จ",
  ERROR_MESSAGE: "เกิดข้อผิดพลาดกรุณาติดต่อเจ้าหน้าที่",
  OK: "ok",
  DUPLICATE: "ข้อมูลซ้ำ",
  SUCCESS: "Success",
  SYNC_SUCCESS: "Sync Successfully",
  STATUS_BOT: "เปลี่ยนสถานะบอท",
  ON: "On",
  OFF: "Off", 
  BOT_START: "บอทเริ่มทำงาน",
  BOT_STOP: "บอทหยุดทำงาน",
  COMPANY_CODE: "Company Code",
  WEBSITE: "Website",
  STATUS: "Status", 
};
